### PR TITLE
Api example inclusions

### PR DESCRIPTION
**Pull request by jposada202020**
This will allow to see all the example listed in the repository in the Readthedocs documentation

### CODE REVIEW

**Review by FoamyGuy — COMMENTED** [review]
These changes to `examples.rst` look good to me. 

But this PR also seems to include some changes from #145. We can either wait until that PR is ready to merge and then bring this one in. Or if you like you could change this PR (or make a new one) that includes the `examples.rst` changes by itself and we could likely merge that sooner.

**Comment by jposada202020** [comment]
@FoamyGuy thanks for reviewing, I think we could wait. this is an improvement and I will made the changes for #145 tonight :)

**Review by FoamyGuy — APPROVED** [review]
Looks good to me. Thank you @jposada202020!

**Comment by jposada202020** [comment]
@FoamyGuy Thank you for reviewing :)

**Pull request merged**
