### PR TITLE
Fix anchor point, anchored_position and scale

### PR DESCRIPTION
**Pull request by kmatch98**
This is to resolve issue #108 where there was an bug for setting anchor_point and anchored_position.  

Main issue was use of getter/setter versus local variable, and sequence of setting any changes to the scale.

### CODE REVIEW

**Comment by FoamyGuy** [comment]
I think your local repo is behind adafruit master atm. So when this branch got started it's missing some of the newest commits from master.

I think I can merge master into this branch and push it here so get it fixed, I'll give that a try.

**Comment by FoamyGuy** [comment]
I think that is resolved now. I'll test this out in a bit.

Thanks for working on this!

**Review by FoamyGuy — APPROVED** [review]
Tested successfully with the "comparison" script in the examples directory, as well as modified bitmap_label_simpletest. 

Looks good to me. Thanks again!

**Comment by kmatch98** [comment]
Thanks @foamyguy!

**Pull request merged**
