### PR TITLE
Anchoring Point relative to the Baseline

### PR DESCRIPTION
**Pull request by jposada202020**
This replace PR #124. Will solve isssue #100.

Logic was tested in Previous PR.  It was tested again using the blinka display for label and bitmap label

These are the results after refactoring. Using the same code presented in PR #124 

image

image.

@FoamyGuy Please review with code in previous PR. Thanks :)

### CODE REVIEW

**Comment by jposada202020** [comment]
This also include replacement for PR #123

**Comment by kmatch98** [comment]
@jposada202020 this is looking really good.  

I noticed errors in the doc strings in the last parameters.  I think you have an extra `:` after `param` that is making it weird.  It's the same issue on both label and bitmap_label.

This is a great addition, thanks again for all your work on this.

On label:
image

On bitmap_label:
image

**Comment by jposada202020** [comment]
@kmatch98 Thanks for the review and comments, I will work on those changes,You are on point there are two ":" 
 did you generate the document using sphinx?
I just want to make sure I am verifying that everythng is ok  when correcting those changes

**Comment by kmatch98** [comment]
I didn't build it locally, I just noticed it on the "official" released docs.  

If you've never build Sphinx documents, you can setup the build the Sphinx docs locally and verify them ([here's the guide](https://learn.adafruit.com/creating-and-sharing-a-circuitpython-library/sharing-our-docs-on-readthedocs)).

Go into the docs folder and then the main command to build them is `sphinx-build -E -W -b html . _build/html`.

**Comment by jposada202020** [comment]
Thanks for the Infor I will check that out!

**Comment by jposada202020** [comment]
Corrections in this commit https://github.com/adafruit/Adafruit_CircuitPython_Display_Text/pull/135/commits/f6d19be7c098d2920332d452dd75461bd3427131

**Review by FoamyGuy — APPROVED** [review]
Thanks for this great new feature @jposada202020! 

I tested these changes successfully (both .py and .mpy versions) on:
```
Adafruit CircuitPython 6.2.0-beta.3-36-g103632f44 on 2021-03-07; Adafruit PyPortal with samd51j2
```
as well as Blinka_Displayio using the supplied test script from the linked older PR.

These changes look good to me. the `baseline` value for `anchor_point` feature is a really nice addition. Thanks for adding the type hints as well, this will be a big help in pycharm.

I made one extra tiny commit to remove the extra colons mentioned in the doc strings. I think that commit you linked was to a different branch or something. I fixed those up and checked the sphinx docs output and it's looking nice now to me.

**Comment by jposada202020** [comment]
@FoamyGuy Thanks, yes I noticed that, the commit is in the Vertical Label branch, Thank you for the review and made the changes.

**Pull request merged**
